events {
    worker_connections 1024;
}

http {
    # Tipos de arquivo
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Servidor
    server {
        listen 4200;
        server_name _;

        # Pasta onde os arquivos compilados estão
        root /usr/share/nginx/html;
        index index.html;

        # Todas as rotas caem em index.html (Angular routing)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API - redireciona para backend
        location /api/ {
            proxy_pass http://backend:8080/;
        }

        # Cache para assets estáticos
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}
